# Config file untuk model TwoStream_Cosign dengan setting signer independent (si)
work_dir: ./work_dir/si/ # direktori untuk menyimpan model dan log
device: 0 # device untuk training, bisa berupa int (misal 0 untuk GPU 0) atau string (misal 'cuda:0' atau 'cpu')
phase: train # fase untuk menjalankan skrip, bisa berupa 'train' atau 'test'
save_interval: 1 # interval untuk menyimpan model, dalam satuan epoch
random_seed: 123 # seed untuk memastikan hasil yang dapat direproduksi
eval_interval: 1 # interval untuk evaluasi model, dalam satuan epoch
log_interval: 100 # interval untuk mencetak log, dalam satuan iterasi
evaluate_tool: sclite # alat untuk evaluasi, bisa berupa 'sclite' atau 'wer'

# feeder args untuk memuat data, dalam hal ini menggunakan SkeletonFeeder untuk dataset mslr_iccv_si yang merupakan dataset signer independent (si)
feeder: SkeletonFeeder # jenis feeder yang digunakan untuk memuat data, dalam hal ini menggunakan SkeletonFeeder untuk dataset mslr_iccv_si yang merupakan dataset signer independent (si)
# [si] for signer independent and [us] for unseen sentence
dataset: mslr_iccv_si # nama dataset yang digunakan, dalam hal ini menggunakan mslr_iccv_si yang merupakan dataset signer independent (si)
num_worker: # jumlah worker untuk memuat data, disarankan untuk menggunakan jumlah yang sesuai dengan jumlah CPU yang tersedia untuk mempercepat proses loading data 
feeder_args: # argumen untuk feeder, dalam hal ini menggunakan SkeletonFeeder untuk dataset mslr_iccv_si yang merupakan dataset signer independent (si)
  setting: si # setting untuk dataset, dalam hal ini menggunakan signer independent (si)
  datatype: skeleton # jenis data yang digunakan, dalam hal ini menggunakan data skeleton
  split: &split [25, 46, 67, 86] # pembagian data untuk training, validation, dan testing, dalam hal ini menggunakan pembagian 25% untuk training, 21% untuk validation, dan 21% untuk testing, dengan 33% data yang tidak digunakan
  norm_point: [0, 25, 46, 67] # titik normalisasi untuk data skeleton, dalam hal ini menggunakan titik 0, 25, 46, dan 67 untuk normalisasi data skeleton
  used_part: &used_part ['body', 'hand21', 'mouth_8'] # bagian tubuh yang digunakan untuk model, dalam hal ini menggunakan bagian tubuh, tangan, dan mulut dengan 8 titik untuk model TwoStream_Cosign

# model args

# load_weights:

model: TwoStream_Cosign # jenis model yang digunakan, dalam hal ini menggunakan model TwoStream_Cosign untuk dataset signer independent (si)
model_args: # argumen untuk model, dalam hal ini menggunakan argumen untuk model TwoStream_Cosign yang sesuai dengan dataset signer independent (si)
  visual_args: # argumen untuk stream visual, dalam hal ini menggunakan argumen untuk stream visual yang sesuai dengan dataset signer independent (si)
    in_channels: 2 # jumlah channel input untuk stream visual, dalam hal ini menggunakan 2 channel untuk data skeleton (x dan y)
    split: *split # pembagian data untuk stream visual, dalam hal ini menggunakan pembagian yang sama dengan feeder untuk stream visual
    temporal_kernel: 5 # ukuran kernel temporal untuk stream visual, dalam hal ini menggunakan ukuran kernel 5 untuk stream visual
    hidden_size: 1024 # ukuran hidden layer untuk stream visual, dalam hal ini menggunakan ukuran hidden layer 1024 untuk stream visual
    modes: *used_part # bagian tubuh yang digunakan untuk stream visual, dalam hal ini menggunakan bagian tubuh, tangan, dan mulut dengan 8 titik untuk stream visual
  motion_args: # argumen untuk stream motion, dalam hal ini menggunakan argumen untuk stream motion yang sesuai dengan dataset signer independent (si)
    level: '1' # level untuk stream motion, dalam hal ini menggunakan level 1 untuk stream motion
    adaptive: True # apakah menggunakan adaptive untuk stream motion, dalam hal ini menggunakan adaptive untuk stream motion
    CR_args: # argumen untuk CR block, dalam hal ini menggunakan argumen untuk CR block yang sesuai dengan dataset signer independent (si)
      clip_length: 25 # panjang klip untuk CR block, dalam hal ini menggunakan panjang klip 25 untuk CR block
      ratio: 0.2
  conv_type: K3-P2-K3-P2 # jenis convolution yang digunakan, dalam hal ini menggunakan K3-P2-K3-P2 untuk model TwoStream_Cosign
  loss_weights: # bobot loss untuk berbagai komponen model
    CR_ConvCTC_static: 1.0
    CR_SeqCTC_static: 1.0
    CR_Conv_static: 2.0
    CR_Seq_static: 2.0
    CR_ConvCTC_motion: 1.0
    CR_SeqCTC_motion: 1.0
    CR_Conv_motion: 2.0
    CR_Seq_motion: 2.0
    CR_ConvCTC_fusion: 1.0
    CR_SeqCTC_fusion: 1.0
    CR_Conv_fusion: 2.0
    CR_Seq_fusion: 2.0
  norm_scale: 32 # skala normalisasi untuk model, dalam hal ini menggunakan skala normalisasi 32 untuk model TwoStream_Cosign

# optim args

batch_size:  4 # ukuran batch untuk training, dalam hal ini menggunakan ukuran batch 4 untuk model TwoStream_Cosign dengan dataset signer independent (si)
test_batch_size: 4 # ukuran batch untuk testing, dalam hal ini menggunakan ukuran batch 4 untuk model TwoStream_Cosign dengan dataset signer independent (si)
optimizer_args: # argumen untuk optimizer, dalam hal ini menggunakan argumen untuk optimizer yang sesuai dengan dataset signer independent (si)
  base_lr: 0.0002
  learning_ratio: 1
  nesterov: false
  optimizer: AdamW
  start_epoch: 0
  step:
  - 20
  - 35
  weight_decay: 0.0001
num_epoch: 40